package dvfpay

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	IncomeGatewayApi
	PayoutGatewayApi
	IncomeOrderApi
	PayoutOrderApi
	MerchantFundsApi
	ExchangeRateApi
	ExchangeRecordApi
	TransactionApi
	TransactionRecordApi
	IncomeGatewayAuthApi
	PayoutGatewayAuthApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
