package dvfpay


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	IncomeGatewayService
	PayoutGatewayService
	IncomeOrderService
	PayoutOrderService
	MerchantFundsService
	ExchangeRateService
	ExchangeRecordService
	TransactionService
	TransactionRecordService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

