package dvfpay

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	IncomeGatewayRouter
	PayoutGatewayRouter
	IncomeOrderRouter
	PayoutOrderRouter
	MerchantFundsRouter
	ExchangeRateRouter
	ExchangeRecordRouter
	TransactionRouter
	TransactionRecordRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
